
DROP TABLE IF EXISTS item_categories CASCADE;
CREATE TABLE item_categories (
 id SERIAL PRIMARY KEY NOT NULL,
 item_id INTEGER REFERENCES items(id) ON DELETE CASCADE,
 category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE
);
